-- ============================================================================
-- PUBLIC SCHEMA - Application Tables
-- ============================================================================

CREATE TABLE IF NOT EXISTS book (
    id BIGINT PRIMARY KEY,
    title TEXT NOT NULL,
    issued DATE,
    subjects TEXT
);

CREATE TABLE IF NOT EXISTS author (
    id BIGSERIAL PRIMARY KEY,
    last_name VARCHAR(255),
    first_names VARCHAR(255),
    birth_year INTEGER,
    death_year INTEGER,
    normalized_key VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS book_author (
    book_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, author_id),
    CONSTRAINT fk_book_author_book
        FOREIGN KEY (book_id)
        REFERENCES book (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_book_author_author
        FOREIGN KEY (author_id)
        REFERENCES author (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_book_author_author_id
    ON book_author (author_id);

CREATE TABLE IF NOT EXISTS language (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS book_language (
    book_id BIGINT NOT NULL,
    language_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, language_id),
    CONSTRAINT fk_book_language_book
        FOREIGN KEY (book_id)
        REFERENCES book (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_book_language_language
        FOREIGN KEY (language_id)
        REFERENCES language (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_book_language_language_id
    ON book_language (language_id);

CREATE TABLE IF NOT EXISTS facet (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    label VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS facet_value (
    id BIGSERIAL PRIMARY KEY,
    facet_id BIGINT NOT NULL,
    raw_value TEXT NOT NULL,
    normalized_value TEXT NOT NULL,
    CONSTRAINT fk_facet_value_facet
        FOREIGN KEY (facet_id)
        REFERENCES facet (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_facet_value UNIQUE (facet_id, normalized_value)
);

CREATE TABLE IF NOT EXISTS book_facet_value (
    book_id BIGINT NOT NULL,
    facet_value_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, facet_value_id),
    CONSTRAINT fk_book_facet_value_book
        FOREIGN KEY (book_id)
        REFERENCES book (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_book_facet_value_value
        FOREIGN KEY (facet_value_id)
        REFERENCES facet_value (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_facet_value_facet_id
    ON facet_value (facet_id);

CREATE INDEX IF NOT EXISTS idx_book_facet_value_value_id
    ON book_facet_value (facet_value_id);

-- ============================================================================
-- SYSTEM SCHEMA - Spring Batch Infrastructure
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS syst;

CREATE SEQUENCE IF NOT EXISTS syst.BATCH_JOB_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS syst.BATCH_JOB_EXECUTION_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS syst.BATCH_STEP_EXECUTION_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS syst.BATCH_JOB_INSTANCE_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS syst.BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    CONSTRAINT BATCH_JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

CREATE TABLE IF NOT EXISTS syst.BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP(9) NOT NULL,
    START_TIME TIMESTAMP(9) DEFAULT NULL,
    END_TIME TIMESTAMP(9) DEFAULT NULL,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP(9),
    CONSTRAINT BATCH_JOB_INST_EXEC_FK
        FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES syst.BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS syst.BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(100) NOT NULL,
    PARAMETER_VALUE VARCHAR(2500),
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT BATCH_JOB_EXEC_PARAMS_FK
        FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES syst.BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS syst.BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP(9) NOT NULL,
    START_TIME TIMESTAMP(9) DEFAULT NULL,
    END_TIME TIMESTAMP(9) DEFAULT NULL,
    STATUS VARCHAR(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    EXIT_CODE VARCHAR(2500),
    EXIT_MESSAGE VARCHAR(2500),
    LAST_UPDATED TIMESTAMP(9),
    CONSTRAINT BATCH_JOB_EXEC_STEP_FK
        FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES syst.BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS syst.BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT BATCH_STEP_EXEC_CTX_FK
        FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES syst.BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS syst.BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    CONSTRAINT BATCH_JOB_EXEC_CTX_FK
        FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES syst.BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE INDEX IF NOT EXISTS BATCH_JOB_INST_EXEC_FK_IDX
    ON syst.BATCH_JOB_EXECUTION (JOB_INSTANCE_ID);

CREATE INDEX IF NOT EXISTS BATCH_STEP_EXEC_JOB_FK_IDX
    ON syst.BATCH_STEP_EXECUTION (JOB_EXECUTION_ID);